### ISSUE TITLE
No Glyphs App sources this time?

### ISSUE THREAD

**Issue by weiweihuanghuang** [Omnibus-Type/ArchivoNarrow#1]

**Comment by Omnibus-Type** [comment]
Hi Wei H. Of course you have access to different Glyphs App source files, only that we are put all source files inside of SRC folder, the path is the following:
https://github.com/Omnibus-Type/Archivo-Devanagari/blob/master/Devanagari-in-progress/SRC/Archivo%20Narrow%20Devanagari-MM.glyphs
