### ISSUE TITLE
Too big space between "di"

### ISSUE THREAD

**Issue by petanc** [Omnibus-Type/ArchivoNarrow#7]
Hi, I have problem with spacing between character "d" and "i" in one word, e.g. [google fonts](https://fonts.google.com/specimen/Archivo+Narrow?query=archiv&preview.text=aim,+bim,+cim,+dim,+eim,+fim,+gim,+him,+iim,+jim,+kim,+lim,+mim,+nim,+oim,+pim,+qim,+rim,+sim,+tim,+uim,+vim,+wim,+xim,+yim,+zim&preview.text_type=custom&sidebar.open=true&selection.family=Archivo+Narrow) (bold version is most noticeable). Thanks
![Archivo_Narrow](https://user-images.githubusercontent.com/23531470/89382408-13782e00-d6fb-11ea-80a8-494b6a84a3c3.png)

**Comment by emmamarichal** [comment]
Hi @Omnibus-Type!
Sorry, I forgot to link this issue to the PR, you can close it manually :)

**Comment by petanc** [comment]
> Hi @Omnibus-Type! Sorry, I forgot to link this issue to the PR, you can close it manually :)

Thanks :)
